DRAFT  ink! tutorial
AstarNetwork/astar-docs pull request #197
Opened 2022-12-08 16:48 UTC by PierreOssun

2023-01-04 09:29 UTC, bobo-k2 requested changes
Great work. I went through the tutorial and found and commented some points that could be improved.

2023-01-04 09:29 UTC, bobo-k2 commented on docs/builder-guides/from- zero-to-ink-hero/dex/Factory/factory.md
> +    #[ink(storage)]
Remove tab

2023-01-05 15:26 UTC, PierreOssun commented on docs/builder-guides/from- zero-to-ink-hero/dex/Pair/mint.md
> +        self.data::<data::Data>().price_0_cumulative_last += price_cumulative_last_0;
By design =)
The UniswapV2Pair cumulative price variables are designed to eventually overflow, i.e. price0CumulativeLast and price1CumulativeLast and blockTimestampLast will overflow through 0.
https://docs.uniswap.org/contracts/v2/guides/smart-contract-integration/building-an-oracle

2023-01-06 09:55 UTC, Maar-io commented on docs/builder-guides/from- zero-to-ink-hero/dex/uniswap-v2-dex-in-ink.md
> +- to have knowledge about AMM & [Uniswap V2 implementation](https://docs.uniswap.org/contracts/v2/overview) (as this tutorial will fucos on implementation)
fucos :)

2023-01-06 14:00 UTC, Maar-io commented
chapters before block code are sometimes ending with `:` and sometimes without it. Can you make it consistent?

2023-01-06 14:02 UTC, Maar-io commented
Can you add some light into why `data::<MyType>()` is called as function

2023-01-09 16:09 UTC, PierreOssun commented
> Can you add some light into why data::<MyType>() is called as function
Explanation is here:
https://github.com/Supercolony-net/openbrush-contracts/blob/e366f6ff1e5892c6a624833dd337a6da16a06baa/lang/src/traits.rs#L63

I think this is really advanced Rust and will not bring value for a tutorial. But advanced developer will check the Trait anyway if they need to understand

2023-01-15 20:00 UTC, fiexer approved these changes

2023-01-16 08:59 UTC, bobo-k2 approved these changes
LGTM

2023-01-16 16:35 UTC, merged