Brushfam info
AstarNetwork/astar-docs pull request #215
Opened 2022-12-29 12:01 UTC by coreggon11

This PR contains updated info about openbrush, and we also mention other brushfam infrastructure tools

2022-12-30 11:27 UTC, hoonsubin requested changes

2022-12-30 11:27 UTC, hoonsubin commented on docs/wasm/sc-dev/use-openbrush.md
> +You can join the [Brushfam Element channel](https://matrix.to/#/!utTuYglskDvqRRMQta:matrix.org?via=matrix.org&via=t2bot.io&via=web3.foundation) if you have any question about OpenBrush or ink! smart
We generally don't allow adding SNS links directly to our docs. Could you add the link to the READ of the tools instead?

2022-12-30 11:27 UTC, hoonsubin commented on docs/wasm/sc-dev/tools.md
> +You can join the [Brushfam Element channel](https://matrix.to/#/!utTuYglskDvqRRMQta:matrix.org?via=matrix.org&via=t2bot.io&via=web3.foundation) if you have any question about some of the mentioned to
same case here

2022-12-30 16:29 UTC, coreggon11 commented
@hoonsubin thanks for the response, I removed the sns links

2022-12-30 16:55 UTC, hoonsubin approved these changes
@fiexer please review this too

2023-01-11 11:03 UTC, coreggon11 commented
@hoonsubin @fiexer Hello guys, any updates here?

2023-01-11 13:13 UTC, fiexer commented
Blocker is on my end, I'll have it done EOW 🙏

2023-01-11 17:41 UTC, coreggon11 commented
@fiexer thanks for the reply 😄 sure, take your time

2023-01-19 15:43 UTC, fiexer approved these changes

2023-01-19 15:43 UTC, merged