added(config): recommended node version config files
AstarNetwork/astar-docs pull request #222
Opened 2023-01-04 18:13 UTC by TomaszWaszczyk

2023-01-16 08:50 UTC, hoonsubin requested changes
Is there a reason why you chose `16.17.0`?
How about using the latest stable LTS version (`18`)?

Note that you also have to update the GitHub action workflow

2023-01-16 09:25 UTC, TomaszWaszczyk commented
My logic was to select the lowest version that works on my machine.

Already changed to suggested `18`.

2023-02-01 10:47 UTC, fiexer commented
@hoonsubin can you finish reviewing this PR.

2023-02-01 10:48 UTC, hoonsubin approved these changes

2023-02-01 19:01 UTC, merged