Added `You own EVM RPC` section into tooling
AstarNetwork/astar-docs pull request #234
Opened 2023-01-19 07:08 UTC by akru

**Description**

Short section about running own EVM RPC. 
Changes from https://github.com/AstarNetwork/Astar/pull/833 adopted.

2023-01-19 07:29 UTC, Dinonard requested changes
Just some grammar improvements (Maarten will probably override me though :grin:).

And I recommend using `::note` to emphasize the fact EVM rpc is disabled by default.

2023-01-19 07:29 UTC, Dinonard commented on docs/EVM/developer-tooling.md
> +For EVM developers and projects could be reasonable to have own EVM endpoints. In case of using public endpoints the project will depend of this endpoint, centralized EVM RPC can become single point
```suggestion
For EVM developers and projects, it is reasonable to have their own managed EVM endpoints. Relying on public endpoints introduces, introduces the risk of relying on centralized endpoints which can become single point of failure.

Astar team officially recommends projects to use their own managed EVM endpoints.
```

2023-01-19 07:29 UTC, Dinonard commented on docs/EVM/developer-tooling.md
> +Fortunately launch Astar Network endpoint is not that difficult.
```suggestion
Fortunately, launching Astar Network endpoint is not that difficult.
```

2023-01-19 07:29 UTC, Dinonard commented on docs/EVM/developer-tooling.md
> +> By default EVM RPC server is disabled, for turn it on please add `--enable-evm-rpc` flag into launch string.
```suggestion
:::note
By default EVM RPC server is disabled, to turn it on please add `--enable-evm-rpc` flag into the launch string.
:::
```

I think you should mention this in the chapter which describes operating a node in general.

2023-01-19 07:29 UTC, Dinonard commented on docs/EVM/developer-tooling.md
> +Launch string above start Astar Collator for Shiden network. HTTP endpoint becomes available on port `9933` and WS on port `9944`.
```suggestion
Launch string above will start Astar Collator for Shiden network. HTTP endpoint becomes available on port `9933` and WS on port `9944`.
```

2023-01-19 07:29 UTC, Dinonard commented on docs/EVM/developer-tooling.md
> +We also could recommend take attention to `--ws-max-connections` parameter, by default it relatively small and you probably would increase it to couple of thousands.
```suggestion
We also recommend to pay attention to the `--ws-max-connections` parameter. By default it relatively small and you will probably want to increase it to couple of thousands.
```

2023-01-20 08:29 UTC, akru commented
Thank you @Dinonard

2023-01-23 05:59 UTC, merged