Feature/flipper
AstarNetwork/astar-docs pull request #237
Opened 2023-01-20 17:47 UTC by hilarious23

2023-01-20 18:00 UTC, bobo-k2 requested changes

2023-01-20 18:00 UTC, bobo-k2 commented on docs/builder-guides/from-zero-to-ink-hero/flipper-contract/flipper-contract.md
> +[flipper(wasm-showcase-dapps)](https://github.com/AstarNetwork/wasm-showcase-dapps/tree/main/flipper)
Broken link

2023-01-20 18:00 UTC, bobo-k2 commented on docs/builder-guides/from-zero-to-ink-hero/flipper-contract/flipper-contract.md
> +[I. File & Folder structure of the project](./Structure/file-structure.md)
Looks like this one is broken too

2023-01-20 18:06 UTC, bobo-k2 commented on docs/builder-guides/from-zero-to-ink-hero/flipper-contract/flipper-contract.md
> +cd wasm-showcase-dapps/flipper
I can't find `flipper` folder in `wasm-showcase-dapps`

2023-01-20 19:11 UTC, hilarious23 commented
I removed flipper from wasm-showcase and create dedicated repo.
https://github.com/AstarNetwork/wasm-flipper



On Fri, Jan 20, 2023 at 19:07 Bobo ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> docs/builder-guides/from-zero-to-ink-hero/flipper-contract/flipper-contract.md
> <https://github.com/AstarNetwork/astar-docs/pull/237#discussion_r1082901889>
> :
>
> > +2. Deploy the contract with Swanky and get the contract address
> +3. Run the app
> +4. Set the contract address
> +5. Login with wallet
> +6. flip and get result
> +
> +### Setting
> +
> +Clone repo
> +
> +```bash
> +git clone https://github.com/AstarNetwork/wasm-showcase-dapps
> +```
> +and Install dependencies by running `yarn`
> +```bash
> +cd wasm-showcase-dapps/flipper
>
> I can't find flipper folder in wasm-showcase-dapps
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AstarNetwork/astar-docs/pull/237#pullrequestreview-1264112073>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH53TJX6X2HZNHEFL235SV3WTLH45ANCNFSM6AAAAAAUBZCG4Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-01 19:17 UTC, fiexer commented
Any updates on the changes @hilarious23 ?

2023-02-17 09:27 UTC, andabak requested changes
@hilarious23 can you rebase this to main branch (big changes after PR253 merged) - new Build chapter.

cc: @bobo-k2 @niklabh

2023-02-21 14:02 UTC, Maar-io commented
This PR will be replaced with the updates in Flipper tutorial for for ink4! 
@ashutoshvarma please consider these changes in your PR for Flipper ink4, and then cancel this PR.

2023-03-09 10:51 UTC, closed without merging