add modular blockchain info
AstarNetwork/astar-docs pull request #570
Opened 2024-01-09 19:38 UTC by meganskye

update zkEVM sections

2024-01-10 08:43 UTC, andabak requested changes

2024-01-10 08:43 UTC, andabak commented on docs/build/zkEVM/index.md
>  ## What is Astar zkEVM?
@meganskye why would you repeat exactly the same text in Learn (What is Astar zkEVM) and Build (So, What is Astar zkEVM) Chapters?

2024-01-10 08:43 UTC, andabak commented on docs/build/zkEVM/index.md
> +Astar zkEVM is a modular Layer-2 scaling solution leveraging Polygon's zero-knowledge rollups combined with Avail's validium-based storage to facilitate off-chain execution and data availability, wit
@meganskye I don't think Avail info is something publicly communicated yet. Please verify with the team.
If it is, some external links can be added for reference.

2024-02-29 00:35 UTC, meganskye commented
this is now mostly irrelevant

2024-02-29 00:35 UTC, closed without merging