docs: added `transfer-tokens` page
AstarNetwork/astar-docs pull request #76
Opened 2022-09-06 09:21 UTC by impelcrypto

* feat: added `transfer-tokens` page 
  * Related: https://github.com/AstarNetwork/astar-docs/pull/74 
    * I've created new PR since I can't access to the branch above

2022-09-06 13:30 UTC, Kahonnohak commented
Would it be possible to add this to this PR? If so please do.

<meta name=“description” content=“Documentation of Astar and Shiden Network - The Future of Smart Contracts for Multichain - both WebAssembly (WASM) and EVM using XCM. Tutorials, user guides and tools for developers and builders.“>

2022-09-06 13:57 UTC, impelcrypto commented
@Kahonnohak updated!

2022-09-06 14:30 UTC, Kahonnohak commented
mmmm I think some layouts are now broken.

2022-09-07 02:50 UTC, Kahonnohak commented
I don't know what is wrong but this link is not working. Please help. Thanks!
<img width="1321" alt="Screenshot 2022-09-07 at 11 48 53" src="https://user-images.githubusercontent.com/77480847/188777770-86285dce-a9af-4b20-aacc-3649eb808abc.png">

2022-09-07 03:59 UTC, impelcrypto commented
@Kahonnohak  Fixed.

> I don't know what is wrong but this link is not working. Please help. Thanks!

Because there was a space [here](https://github.com/AstarNetwork/astar-docs/pull/76/commits/413655798f738da5403ae8432c1dd04f077d3804#diff-bd68bd13a14f3362fb81f4841d35625713fd40b9ec5ec7df0a1f7531f1b5da60L96).

2022-09-07 04:15 UTC, Kahonnohak commented
Thank you😭

2022-09-07 04:16 UTC, Kahonnohak approved these changes
LGTM

2022-09-07 07:59 UTC, andabakus requested changes
There is one broken link (cannot understand why is not working.) 
maybe @impelcrypto will identify why?

the one in https://astar-docs--pr76-feat-added-new-trans-x5i7u5k2.web.app/docs/user-guides/setup-metamask

![image](https://user-images.githubusercontent.com/95318860/188823331-b6caab35-8570-4206-8898-493db8d5f6a6.png)

2022-09-07 08:17 UTC, impelcrypto commented on docs/user-guides/setup-metamask.md
> +Adding Astar Network to Metamask is very easiy.
I've fixed in [this](https://github.com/AstarNetwork/astar-docs/pull/76/commits/562c2f61ed33d0d4c33636725ef2e6607bd98c24) commit.

2022-09-07 08:24 UTC, impelcrypto commented on docs/user-guides/setup-metamask.md
> +1. You will just need to go to [our Portal](https://portal.astar.network/) and try to connect to Metamask.
It works on my end. Please test it again.
https://gyazo.com/fe33f1900bb490f2067558cfbdd0fb31

2022-09-07 12:29 UTC, andabakus commented on docs/user-guides/setup-metamask.md
> +1. You will just need to go to [our Portal](https://portal.astar.network/) and try to connect to Metamask.
Now it seems it works on my side as well 👍

2022-09-07 12:29 UTC, andabakus approved these changes

2022-09-09 00:53 UTC, merged